### ISSUE TITLE
Pod install fails for the Sample App

### ISSUE THREAD

**Issue by ed-mejia** [box/box-ios-browse-sdk#112]
Running pod install for the sample App returns:

`Analyzing dependencies
[!] The dependency `box-ios-browse-sdk (from `../`)` is not used in any concrete target.`

Cocoapods version: **1.1.0.rc.3**

Pod file needs to be updated to:

```
use_frameworks!
platform :ios, '8.0'

target 'BoxBrowseSDKSampleApp' do
    pod 'box-ios-browse-sdk'
end
```

**Comment by crousselle** [comment]
Hi @ed-mejia,
Thanks for the pointer, appreciate it ! We'll make the necessary updates. 
Have a great weekend.

**Comment by Roshanalexander** [comment]
I'm getting the same error.
