### ISSUE TITLE
BoxBrowseSDKResources is missing

### ISSUE THREAD

**Issue by nhattieunhatkiem** [box/box-ios-browse-sdk#34]
UIImage+BOXBrowseSDKAdditions.m line 52, resourcesBundleURL is null and app crashed

        NSURL *resourcesBundleURL = [[NSBundle mainBundle] URLForResource:@"BoxBrowseSDKResources" withExtension:@"bundle"];

I used use_frameworks! config inside podfile, does it cause this issue ?
I'm using BoxPreviewSDKResources for temporary now.

**Comment by boxtcarpel** [comment]
Are you seeing the same issue the sample app?

**Comment by boxtcarpel** [comment]
@nhattieunhatkiem Please let us know if you are still experiencing issue or need additional help.
