### ISSUE TITLE
BOXFolderViewController hidden search bar

### ISSUE THREAD

**Issue by RafaelKayumov** [box/box-ios-browse-sdk#57]
Hi.
Having a gap between navigation bar and top cell in BOXFolderViewController. Search bar is placed there as table view header but it's being hidden and never brought back to visible.
This line from `setupForSearch` method hides it:
`self.searchController.searchBar.hidden = YES; // Starts of hidden, and only when we've fetched items do we bring it in.`
I think it should set to visible somewhere in fetchItems completion block. Or do I miss something?
Thanks.

**Comment by jdizoglio** [comment]
Thank you very much. The CR is pending:
https://github.com/box/box-ios-browse-sdk/pull/61

Please let me know if this addresses your issue.

**Comment by RafaelKayumov** [comment]
@jdizoglio, yes, it's related to my issue. But, as far as I see, It doesn't fix it. In code search bar still not being revealed (at least the gap is gone). `self.searchController.searchBar.hidden` never set to `NO`. There is a check in new code:
```
if (self.searchController.searchBar.hidden) {
    self.tableView.tableHeaderView = nil;
} else {
    self.tableView.tableHeaderView = self.searchController.searchBar;
}
```
So the `else` case will not be fired and search bar will still be hidden.
Under this scenario, I guess `self.searchController.searchBar.hidden` should be set to `NO` in callback when items count > 0
Currently I have `folderViewControllerShouldShowSearchBar` delegate method which always returns true, but search bar is not displayed.

**Comment by jdizoglio** [comment]
@RafaelKayumov. I misunderstood the folder class use. The correction is in the latest commit. Thank you for being patient and for reviewing the code!!!

https://github.com/box/box-ios-browse-sdk/pull/64

**Comment by RafaelKayumov** [comment]
@jdizoglio, looks fixed now. Thanks.
